import { z } from "zod";
import { ERAS, SonicPaletteSchema } from "@/lib/intent/schema";
import agentsJson from "@/fixtures/agents.json";
import albumsJson from "@/fixtures/albums.json";
import releasesJson from "@/fixtures/releases.json";
import tapesJson from "@/fixtures/tapes.json";
import tracksJson from "@/fixtures/tracks.json";

/**
 * The archive's read layer. If DATABASE_URL is set, reads come from Neon
 * (mirroring the kernel's append-only log); otherwise — and whenever a
 * query fails, e.g. before the tables exist — everything falls back to the
 * checked-in fixtures. Every page must work with zero env vars.
 */

export const PLAYER_IDS = ["silt", "rust", "keep"] as const;
export const STAFF_IDS = ["muse", "producer", "critic", "listener", "archivist"] as const;
export type PlayerId = (typeof PLAYER_IDS)[number];

/** Where an imported act lives: origin scene + street residence (null = in town). */
export const ResidentSchema = z.object({
  origin: z.string().min(1),
  building: z.string().min(1).nullable(),
});

/** An imported act's back catalogue: one release-shaped id + album facts.
 * Import albums live on the agent row, NOT in the releases table — the
 * releases table stays sessions-only so every deployed reader keeps parsing. */
export const AlbumSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1).optional(),
  /** The Archivist's "what this record is" — back-of-sleeve prose for the
   * record an act brought to town. Optional: rows written before the vault
   * opened (and acts whose notes are still unwritten) keep parsing. */
  linerNotes: z.string().min(1).optional(),
});

export const AgentSchema = z
  .object({
    id: z.string().min(1),
    kind: z.enum(["player", "staff"]),
    /** Stable sub-identity (the mineral slug for acts, the title for staff). */
    name: z.string().min(1),
    /** Public stage name. Optional in the data so pre-rename DB rows still parse. */
    displayName: z.string().min(1).optional(),
    role: z.string().min(1),
    stance: z.string().min(1),
    description: z.array(z.string().min(1)),
    /** Press bio — one short paragraph written for strangers (generated by
     * web/scripts/generate_bios.mjs, reviewed before commit). Optional so
     * pre-bio DB rows still parse; pages fall back to `description`. */
    bio: z.string().min(1).optional(),
    palette: SonicPaletteSchema.nullable(),
    /** Portrait slot — the act's press photo in Neon media; pages fall back to public/press/. */
    imageUrl: z.string().min(1).nullable().optional(),
    /** Album-cover slot for imported acts (their back-catalogue sleeve). */
    coverUrl: z.string().min(1).nullable().optional(),
    /** "dub techno · 2020s" — the imported act's genre-and-era line. */
    genreLine: z.string().min(1).optional(),
    /** The stance translated for strangers (house acts carry this in ACT_DESIGN). */
    descriptor: z.string().min(1).optional(),
    /** Present only on imported acts; house acts and staff carry nothing. */
    resident: ResidentSchema.optional(),
    /** The imported act's back catalogue (release id `T-<slug>`). */
    album: AlbumSchema.optional(),
  })
  .transform((a) => ({
    ...a,
    displayName: a.displayName ?? a.name,
    imageUrl: a.imageUrl ?? null,
    coverUrl: a.coverUrl ?? null,
  }));

export const TrackSchema = z.object({
  id: z.string().min(1),
  releaseId: z.string().min(1),
  agentId: z.string().min(1),
  title: z.string().min(1),
  durationSec: z.number().int().positive().nullable(),
  audioUrl: z.string().min(1).nullable(),
  /** The ONE line the artist says about this song (Album.tracks[].note, and
   * the acts' studio line on the round-based takes). No min length: rows have
   * carried an empty string here since before it was surfaced. */
  line: z.string().optional(),
});

export const InfluenceEdgeSchema = z.object({
  from: z.enum(PLAYER_IDS),
  to: z.enum(PLAYER_IDS),
  weight: z.number().min(0).max(1),
});

export const ReleaseSchema = z
  .object({
    id: z.string().min(1),
    title: z.string().min(1),
    era: z.enum(ERAS),
    set: z.number().int().positive(),
    condition: z.string().min(1),
    date: z.string().min(1),
    brief: z.string().min(1),
    selection: z.string().min(1),
    review: z.string().min(1),
    reaction: z.string().min(1),
    /** The Listener's one-word verdict on the release. Optional so releases
     * published before the Listener existed (and fixtures) still parse;
     * missing means nobody from the cheap seats has weighed in. */
    reactionValence: z.enum(["loved", "liked", "mixed", "cold"]).optional(),
    takeIds: z.array(z.string().min(1)),
    /** The Producer's picks, act id -> take id. Only present when a release
     * was actually chosen by the Producer (release 0002 onward); absent means
     * nothing on this release was "the single". */
    selections: z.record(z.string(), z.string().min(1)).optional(),
    influence: z.array(InfluenceEdgeSchema),
    rationales: z.record(z.string(), z.string()),
    /** The Critic's per-act verdicts, keyed by player id. Optional so
     * pre-staff releases (and fixtures) still parse; missing means the
     * Critic has not weighed in on the acts individually. */
    reviews: z.record(z.string(), z.string()).optional(),
    /** Cover slot — AI-image covers arrive later; the release hero shows one when present. */
    coverUrl: z.string().min(1).nullable().optional(),
    /** The Archivist's liner notes — what happened in the room, who did what,
     * what to listen for (distinct from the Critic's review, which judges).
     * Optional so every pre-Archivist row keeps parsing. */
    linerNotes: z.string().min(1).optional(),
  })
  .transform((r) => ({
    ...r,
    coverUrl: r.coverUrl ?? null,
    reviews: r.reviews ?? {},
    selections: r.selections ?? {},
  }));

/** One take on a session tape — every take of the session, not just the cut. */
export const TapeTakeSchema = z.object({
  round: z.number().int().nonnegative(),
  agentId: z.string().min(1),
  /** The Critic's title, present only on takes that made the release. */
  title: z.string().min(1).nullable().optional(),
  audioUrl: z.string().min(1).nullable(),
  durationSec: z.number().int().positive().nullable().optional(),
  /** True when this take is the one the Producer put on the release. */
  selected: z.boolean().optional(),
  /** The act's logged spoken line for this take. */
  line: z.string().optional(),
  /** The Archivist's call-out — why this take earns a listen. */
  callout: z.string().min(1).optional(),
  /** A logged judge dissent — a panel voice that wanted this take released. */
  dissent: z.string().min(1).optional(),
});

/**
 * A session tape (the vault doctrine): one session's FULL recording — every
 * take, in round order — released as its own archive entry, catalogue series
 * TAPE-NNNN. The cut release (when one exists) stays the headline; the tape
 * is the companion. Rejected and abandoned sessions get tapes too — the
 * Producer's veto stands; the tape survives. Tapes live in their own table
 * (`tapes`), so no existing releases row ever meets a shape it cannot parse.
 */
export const TapeSchema = z
  .object({
    id: z.string().min(1),
    kind: z.literal("tape"),
    title: z.string().min(1),
    runId: z.string().min(1),
    /** The release this tape companions; null for standalone tapes. */
    releaseId: z.string().min(1).nullable().optional(),
    date: z.string().min(1),
    condition: z.string().min(1),
    rounds: z.number().int().positive(),
    /** What happened to the session, derived from the log alone. */
    status: z.enum(["released", "rejected", "abandoned", "solo", "unreleased"]),
    /** The Archivist's placement — absent when the tape published unshelved. */
    placement: z.enum(["companion", "standalone", "collection"]).optional(),
    /** The Archivist's one-line arc of the session. */
    arc: z.string().min(1).optional(),
    /** The Archivist's liner notes for the tape. */
    linerNotes: z.string().min(1).optional(),
    /** The Producer's logged 'no release' prose, on rejected sessions. */
    vetoNote: z.string().min(1).optional(),
    takes: z.array(TapeTakeSchema),
  })
  .transform((t) => ({
    ...t,
    releaseId: t.releaseId ?? null,
  }));

/**
 * A single-artist ALBUM — the catalogue's primary object (docs/SPEC.md: the
 * album is the unit of work). One artist writes a whole record in its own
 * voice; the staff only react afterwards.
 *
 * Its own table (`albums`), so no existing releases row ever meets a shape it
 * cannot parse — the same caution the tapes and import PRs took, and the
 * reason one unparseable row can never void the live catalogue. Ids continue
 * the ONE AFAR-NNNN sequence across both tables (AFAR-0008 follows the last
 * session, AFAR-0007), so the public numbering has no seam in it.
 *
 * `artistId` and `description` are the two fields that make this shape what it
 * is: attribution is first-class rather than inferred from a tracklist, and
 * the description is the ARTIST's own framing of the record — it sits where
 * the Critic's title and the Producer's selection note used to sit. Every
 * staff field below is optional, because a record publishes before anyone has
 * reacted to it and each reaction degrades independently.
 */
export const AlbumRecordSchema = z
  .object({
    id: z.string().min(1),
    kind: z.literal("album"),
    title: z.string().min(1),
    /** Whose record this is. One artist, always. */
    artistId: z.string().min(1),
    /** The artist's own words about the record, written with the songs. */
    description: z.string().min(1),
    date: z.string().min(1),
    era: z.enum(ERAS),
    trackIds: z.array(z.string().min(1)),
    /** Records this artist heard before writing — sleeve facts, never verdicts. */
    heard: z
      .array(
        z.object({
          albumId: z.string(),
          artistId: z.string(),
          title: z.string(),
        }),
      )
      .optional(),
    /** Album-cadence influence: which heard record pulled this one, [0,1]. */
    influence: z
      .array(
        z.object({
          from: z.string().min(1),
          to: z.string().min(1),
          weight: z.number().min(0).max(1),
        }),
      )
      .optional(),
    /** The Producer's reaction to the finished record. It books nothing. */
    producerNote: z.string().min(1).optional(),
    /** The Critic's public verdict. It names nothing. */
    review: z.string().min(1).optional(),
    /** The Critic on individual songs, keyed by song title. */
    trackNotes: z.record(z.string(), z.string()).optional(),
    /** The Muse on what the scene is doing alongside this record. */
    sceneNote: z.string().min(1).optional(),
    sceneTheme: z.string().min(1).optional(),
    /** The Listener from the cheap seats. */
    reaction: z.string().min(1).optional(),
    reactionValence: z.enum(["loved", "liked", "mixed", "cold"]).optional(),
    /** The Archivist's back-of-sleeve prose. */
    linerNotes: z.string().min(1).optional(),
    /** Honest notes left by reactions that failed — stage -> what it means. */
    staffDegraded: z.record(z.string(), z.string()).optional(),
    coverUrl: z.string().min(1).nullable().optional(),
  })
  .transform((a) => ({
    ...a,
    heard: a.heard ?? [],
    influence: a.influence ?? [],
    trackNotes: a.trackNotes ?? {},
    staffDegraded: a.staffDegraded ?? {},
    coverUrl: a.coverUrl ?? null,
  }));

export type AlbumRecord = z.infer<typeof AlbumRecordSchema>;

export type Tape = z.infer<typeof TapeSchema>;
export type TapeTake = z.infer<typeof TapeTakeSchema>;

/** "0001" -> "TAPE-0001" — the tape series, beside the releases' AFAR-NNNN. */
export function tapeNumber(tapeId: string): string {
  return `TAPE-${tapeId}`;
}

/** The plain one-line framing a tape's status earns — always honest. */
export function tapeStatusLine(tape: Tape): string {
  switch (tape.status) {
    case "released":
      return "The full session — every take, in the order it was played. The release is the cut; this is everything.";
    case "rejected":
      return "Nothing was released from this session — the Producer's veto stands; the tape survives.";
    case "abandoned":
      return "The session stopped mid-set — a machine failure, not a decision. What was played survives.";
    case "solo":
      return "A solo session — one act, recording alone, before the sessions began.";
    default:
      return "A completed session with no verdict on record.";
  }
}

export type Agent = z.infer<typeof AgentSchema>;

/** The stance word from a role line like "Act — accumulation" — used in kickers next to the id. */
export function stanceWord(agent: Agent): string {
  return agent.role.split("—")[1]?.trim() ?? agent.role;
}

/**
 * Plain-language tooltip for a set-condition chip. The kernel logs short
 * condition codes; scene descriptions ("overcast, distant traffic…") need
 * no gloss and get none.
 */
export function conditionGloss(condition: string): string | undefined {
  switch (condition) {
    case "contact":
      return "Recorded together — each act could hear the others";
    case "isolation":
      return "Recorded alone — no act could hear the others";
    case "parallel":
      return "Recorded side by side — at the same time, but unable to hear each other";
    default:
      return undefined;
  }
}

export type Track = z.infer<typeof TrackSchema>;
export type InfluenceEdge = z.infer<typeof InfluenceEdgeSchema>;
export type Release = z.infer<typeof ReleaseSchema>;

/** Fixtures are validated once at module load — a bad fixture fails the build/test, not a visitor. */
export const fixtureAgents: Agent[] = z.array(AgentSchema).parse(agentsJson);
export const fixtureReleases: Release[] = z.array(ReleaseSchema).parse(releasesJson);
export const fixtureTracks: Track[] = z.array(TrackSchema).parse(tracksJson);
export const fixtureTapes: Tape[] = z.array(TapeSchema).parse(tapesJson);
/** Single-artist albums. Empty until the first record ships — a new table
 * with no rows yet is honest, not an outage. */
export const fixtureAlbumRecords: AlbumRecord[] = z
  .array(AlbumRecordSchema)
  .parse(albumsJson);

/**
 * Thin Neon branch: run a query if DATABASE_URL is set, fall back to
 * fixtures on any failure (tables may not exist yet — no migrations ship
 * with the web layer).
 */
async function fromDb<T>(query: () => Promise<T | null>): Promise<T | null> {
  if (!process.env.DATABASE_URL) return null;
  try {
    return await query();
  } catch {
    return null;
  }
}

type JsonRow = { data: unknown };

async function dbRows(
  table: "agents" | "releases" | "tracks" | "tapes" | "albums",
): Promise<unknown[] | null> {
  const { sql } = await import("@/lib/db");
  const result = (await sql().query(`SELECT data FROM ${table} ORDER BY id`)) as
    | { rows?: JsonRow[] }
    | JsonRow[];
  const rows = Array.isArray(result) ? result : (result.rows ?? []);
  if (rows.length === 0) return null;
  return rows.map((r) => r.data);
}

export async function listAgents(): Promise<Agent[]> {
  const db = await fromDb(async () => {
    const rows = await dbRows("agents");
    return rows ? z.array(AgentSchema).parse(rows) : null;
  });
  return db ?? fixtureAgents;
}

export async function getAgent(id: string): Promise<Agent | null> {
  const agents = await listAgents();
  return agents.find((a) => a.id === id) ?? null;
}

export async function listReleases(): Promise<Release[]> {
  const db = await fromDb(async () => {
    const rows = await dbRows("releases");
    return rows ? z.array(ReleaseSchema).parse(rows) : null;
  });
  return db ?? fixtureReleases;
}

export async function getRelease(id: string): Promise<Release | null> {
  const releases = await listReleases();
  return releases.find((r) => r.id === id) ?? null;
}

export async function listTracks(): Promise<Track[]> {
  const db = await fromDb(async () => {
    const rows = await dbRows("tracks");
    return rows ? z.array(TrackSchema).parse(rows) : null;
  });
  return db ?? fixtureTracks;
}

export async function tracksForAgent(agentId: string): Promise<Track[]> {
  return (await listTracks()).filter((t) => t.agentId === agentId);
}

export async function listTapes(): Promise<Tape[]> {
  const db = await fromDb(async () => {
    const rows = await dbRows("tapes");
    return rows ? z.array(TapeSchema).parse(rows) : null;
  });
  return db ?? fixtureTapes;
}

export async function getTape(id: string): Promise<Tape | null> {
  const tapes = await listTapes();
  return tapes.find((t) => t.id === id) ?? null;
}

/** Every single-artist album, the catalogue's primary object. */
export async function listAlbumRecords(): Promise<AlbumRecord[]> {
  const db = await fromDb(async () => {
    const rows = await dbRows("albums");
    return rows ? z.array(AlbumRecordSchema).parse(rows) : null;
  });
  return db ?? fixtureAlbumRecords;
}

/** The session tape that companions a release, if the vault holds one. */
export function resolveTapeForRelease(tapes: Tape[], releaseId: string): Tape | null {
  return tapes.find((t) => t.releaseId === releaseId) ?? null;
}

export async function tapeForRelease(releaseId: string): Promise<Tape | null> {
  return resolveTapeForRelease(await listTapes(), releaseId);
}

/** Every tape an act plays on, newest first — the act page's shelf. */
export function resolveTapesForAgent(tapes: Tape[], agentId: string): Tape[] {
  return tapes
    .filter((t) => t.takes.some((take) => take.agentId === agentId))
    .sort((a, b) => b.id.localeCompare(a.id));
}

export async function tapesForAgent(agentId: string): Promise<Tape[]> {
  return resolveTapesForAgent(await listTapes(), agentId);
}

export async function tracksForRelease(release: Release): Promise<Track[]> {
  const tracks = await listTracks();
  const byId = new Map(tracks.map((t) => [t.id, t]));
  return release.takeIds
    .map((id) => byId.get(id))
    .filter((t): t is Track => t !== undefined);
}

/** The Critic's verdicts on one act, release by release, newest first. */
export async function criticReviewsForPlayer(
  agentId: string,
): Promise<{ releaseId: string; releaseTitle: string; verdict: string }[]> {
  const releases = await listReleases();
  return releases
    .filter((r) => typeof r.reviews[agentId] === "string")
    .map((r) => ({ releaseId: r.id, releaseTitle: r.title, verdict: r.reviews[agentId] }))
    .reverse();
}

/**
 * The act's single: the Producer's selected take from the newest release
 * that carries a selection for this act. Pure so it's testable; pages call
 * singleForAct below. Returns null when the Producer has never picked for
 * this act (e.g. fixture-only mode, where release 0001 predates the staff).
 */
export function resolveSingle(
  releases: Release[],
  tracks: Track[],
  agentId: string,
): { track: Track; release: Release } | null {
  const byId = new Map(tracks.map((t) => [t.id, t]));
  const newestFirst = [...releases].sort((a, b) => b.id.localeCompare(a.id));
  for (const release of newestFirst) {
    const takeId = release.selections[agentId];
    if (!takeId) continue;
    const track = byId.get(takeId);
    if (track) return { track, release };
  }
  return null;
}

export async function singleForAct(
  agentId: string,
): Promise<{ track: Track; release: Release } | null> {
  const [releases, tracks] = await Promise.all([listReleases(), listTracks()]);
  return resolveSingle(releases, tracks, agentId);
}

/* ————————————————————————————————————————————————————————————————————
 * The Album view: one entity over the catalogue's four shapes.
 *
 * A casual listener sees ARTISTS and ALBUMS. Under the hood an "album" is
 * one of three stored shapes — a session release (AFAR-NNNN), a session
 * tape (TAPE-NNNN, solo tapes included), or an imported back-catalogue
 * album riding its artist's agent row (id T-<slug>, tracks in the tracks
 * table). This is a READ-LAYER unification: nothing migrates, every
 * stored shape keeps its schema, and the views below are derived fresh
 * from the same rows the old pages read.
 *
 * Public ids: the slug is the catalogue number, lowercased — afar-0001,
 * tape-0010, t-lolgorithm. Stable because the underlying ids are stable
 * (CLAUDE.md: entity ids never rename).
 * ———————————————————————————————————————————————————————————————————— */

/**
 * The four shapes in the catalogue:
 * - `record` — a single-artist ALBUM, the primary object now (AFAR-NNNN);
 * - `session` — a round-based multi-artist release, the logged history
 *   (AFAR-0001..0007), append-only and never renamed;
 * - `tape` — a session's full recording (TAPE-NNNN);
 * - `album` — a back-catalogue record an artist brought with them.
 */
export type AlbumType = "record" | "session" | "tape" | "album";

/** One measured pull on a record: which heard album moved it, and how much. */
export interface AlbumPull {
  artistId: string;
  albumId: string;
  title: string;
  weight: number;
}

/** "0001" -> "AFAR-0001" (mirrors lib/acts.catalogueNumber, which imports from here). */
function catalogueNumberOf(releaseId: string): string {
  return `AFAR-${releaseId}`;
}

export interface AlbumTrackView {
  id: string;
  title: string;
  artistId: string;
  durationSec: number | null;
  audioUrl: string | null;
  /** What the artist said about this song, if they said anything. */
  note: string | null;
}

export interface AlbumView {
  /** Public id, used in /album/[slug] URLs. */
  slug: string;
  type: AlbumType;
  /** "AFAR-0001" / "TAPE-0010"; imported albums carry no catalogue number. */
  catalogueNo: string | null;
  title: string;
  /** Every artist on the record, in track order. */
  artistIds: string[];
  /** Sortable release date; imported albums predate the sessions and carry none. */
  date: string | null;
  /** The era line under the title ("2020s"). */
  era: string | null;
  tracks: AlbumTrackView[];
  /**
   * The ARTIST's own framing of the record, written with the songs. Set on
   * single-artist albums; null on the shapes whose sleeve prose was written
   * by someone else (or by nobody).
   */
  description: string | null;
  /** The Archivist's back-of-sleeve prose, whatever shape it rode in on. */
  linerNotes: string | null;
  /** Imported album art; sessions render their graph cover from `influence`. */
  coverUrl: string | null;
  influence: InfluenceEdge[] | null;
  /** Album-cadence influence: which records pulled this one (records only). */
  pulledBy: AlbumPull[];
  /** The depth payload — exactly one of these is set, matching `type`. */
  record: AlbumRecord | null;
  release: Release | null;
  tape: Tape | null;
  importArtistId: string | null;
}

/** The casual-listener word for each album type (the type badge). */
export function albumTypeLabel(type: AlbumType): string {
  switch (type) {
    case "record":
      return "ALBUM";
    case "session":
      return "SESSION";
    case "tape":
      return "TAPE";
    default:
      return "BACK CATALOGUE";
  }
}

/** One plain line saying what a badge means — the tooltip next to it. */
export function albumTypeGloss(type: AlbumType): string {
  switch (type) {
    case "record":
      return "An album one artist wrote and recorded here — every song theirs, named by them";
    case "session":
      return "A finished record cut from one recording session — one take from each artist on it";
    case "tape":
      return "The whole session, every take, in the order it was played";
    default:
      return "A studio album an artist brought with them, made before they arrived";
  }
}

/**
 * "afar-0008" | "afar-0001" | "tape-0010" | "t-lolgorithm" — slugs are
 * lowercased catalogue ids. Single-artist albums and the round-based sessions
 * share the `afar-` slug space because they share ONE id sequence: ids are
 * allocated across both tables, so a slug always resolves to exactly one
 * record and old links never change meaning.
 */
export function albumSlug(type: AlbumType, id: string): string {
  if (type === "record" || type === "session") return `afar-${id}`.toLowerCase();
  if (type === "tape") return `tape-${id}`.toLowerCase();
  return id.toLowerCase();
}

/**
 * One artist's album. The tracklist is `trackIds` in the artist's own order —
 * an album is a sequence, not a set, so the order the record was written in is
 * the order it plays in.
 */
function recordAlbum(record: AlbumRecord, tracks: Track[]): AlbumView {
  const byId = new Map(tracks.map((t) => [t.id, t]));
  const own = record.trackIds
    .map((id) => byId.get(id))
    .filter((t): t is Track => t !== undefined);
  const pulledBy = record.influence
    .filter((e) => e.to === record.artistId)
    .map((e) => {
      const heard = record.heard.find((h) => h.artistId === e.from);
      return {
        artistId: e.from,
        albumId: heard?.albumId ?? "",
        title: heard?.title ?? "",
        weight: e.weight,
      };
    })
    .sort((a, b) => b.weight - a.weight);
  return {
    slug: albumSlug("record", record.id),
    type: "record",
    catalogueNo: catalogueNumberOf(record.id),
    title: record.title,
    artistIds: [record.artistId],
    date: record.date,
    era: record.era,
    tracks: own.map((t) => ({
      id: t.id,
      title: t.title,
      artistId: t.agentId,
      durationSec: t.durationSec,
      audioUrl: t.audioUrl,
      note: t.line?.trim() || null,
    })),
    description: record.description,
    linerNotes: record.linerNotes ?? null,
    coverUrl: record.coverUrl,
    influence: null, // the graph cover is the sessions' three-act figure
    pulledBy,
    record,
    release: null,
    tape: null,
    importArtistId: null,
  };
}

function sessionAlbum(release: Release, tracks: Track[]): AlbumView {
  const byId = new Map(tracks.map((t) => [t.id, t]));
  const takes = release.takeIds
    .map((id) => byId.get(id))
    .filter((t): t is Track => t !== undefined);
  return {
    slug: albumSlug("session", release.id),
    type: "session",
    catalogueNo: catalogueNumberOf(release.id),
    title: release.title,
    artistIds: takes.map((t) => t.agentId),
    date: release.date,
    era: release.era,
    tracks: takes.map((t) => ({
      id: t.id,
      title: t.title,
      artistId: t.agentId,
      durationSec: t.durationSec,
      audioUrl: t.audioUrl,
      note: null,
    })),
    description: null,
    linerNotes: release.linerNotes ?? null,
    coverUrl: null,
    influence: release.influence,
    pulledBy: [],
    record: null,
    release,
    tape: null,
    importArtistId: null,
  };
}

function tapeAlbum(tape: Tape): AlbumView {
  const artistIds: string[] = [];
  for (const take of tape.takes) {
    if (!artistIds.includes(take.agentId)) artistIds.push(take.agentId);
  }
  return {
    slug: albumSlug("tape", tape.id),
    type: "tape",
    catalogueNo: tapeNumber(tape.id),
    title: tape.title,
    artistIds,
    date: tape.date,
    era: null,
    tracks: tape.takes.map((take, i) => ({
      id: `${tape.id}-t${i}`,
      title: take.title ?? `Round ${take.round + 1} take`,
      artistId: take.agentId,
      durationSec: take.durationSec ?? null,
      audioUrl: take.audioUrl,
      note: null,
    })),
    description: null,
    linerNotes: tape.linerNotes ?? null,
    coverUrl: null,
    influence: null,
    pulledBy: [],
    record: null,
    release: null,
    tape,
    importArtistId: null,
  };
}

function importAlbum(agent: Agent, tracks: Track[]): AlbumView | null {
  if (!agent.album) return null;
  const own = tracks.filter((t) => t.releaseId === agent.album!.id);
  if (own.length === 0) return null; // no audio imported yet — nothing to stream
  return {
    slug: albumSlug("album", agent.album.id),
    type: "album",
    catalogueNo: null,
    title: agent.album.title,
    artistIds: [agent.id],
    date: null,
    era: agent.genreLine?.split("·")[1]?.trim() ?? null,
    tracks: own.map((t) => ({
      id: t.id,
      title: t.title,
      artistId: t.agentId,
      durationSec: t.durationSec,
      audioUrl: t.audioUrl,
      note: null,
    })),
    description: null,
    linerNotes: agent.album.linerNotes ?? null,
    coverUrl: agent.coverUrl,
    influence: null,
    pulledBy: [],
    record: null,
    release: null,
    tape: null,
    importArtistId: agent.id,
  };
}

/**
 * Every album in the catalogue, one flat list: dated records (single-artist
 * albums, sessions and tapes) newest first, then the imported back catalogues
 * (undated — they predate the sessions) alphabetically. Pure so it's testable.
 */
export function resolveAlbums(
  agents: Agent[],
  releases: Release[],
  tapes: Tape[],
  tracks: Track[],
  records: AlbumRecord[] = [],
): AlbumView[] {
  const dated = [
    ...records.map((r) => recordAlbum(r, tracks)),
    ...releases.map((r) => sessionAlbum(r, tracks)),
    ...tapes.map(tapeAlbum),
  ].sort(
    (a, b) => (b.date ?? "").localeCompare(a.date ?? "") || b.slug.localeCompare(a.slug),
  );
  const imports = agents
    .flatMap((a) => importAlbum(a, tracks) ?? [])
    .sort((a, b) => a.title.localeCompare(b.title));
  return [...dated, ...imports];
}

export async function listAlbums(): Promise<AlbumView[]> {
  const [agents, releases, tapes, tracks, records] = await Promise.all([
    listAgents(),
    listReleases(),
    listTapes(),
    listTracks(),
    listAlbumRecords(),
  ]);
  return resolveAlbums(agents, releases, tapes, tracks, records);
}

export function resolveAlbum(albums: AlbumView[], slug: string): AlbumView | null {
  const wanted = slug.toLowerCase();
  return albums.find((a) => a.slug === wanted) ?? null;
}

export async function getAlbum(slug: string): Promise<AlbumView | null> {
  return resolveAlbum(await listAlbums(), slug);
}

/**
 * An artist's discography: every album they appear on, in the flat
 * catalogue order (newest dated first, their imported record last).
 */
export function resolveDiscography(albums: AlbumView[], artistId: string): AlbumView[] {
  return albums.filter((a) => a.artistIds.includes(artistId));
}

export async function discographyForArtist(artistId: string): Promise<AlbumView[]> {
  return resolveDiscography(await listAlbums(), artistId);
}

/** ONE flat roster — every artist, alphabetical. No sections, no tiers. */
export function resolveArtists(agents: Agent[]): Agent[] {
  return agents
    .filter((a) => a.kind === "player")
    .sort((a, b) => a.displayName.localeCompare(b.displayName));
}

export async function listArtists(): Promise<Agent[]> {
  return resolveArtists(await listAgents());
}

/**
 * The flat roster ordered by latest activity: whoever appears on the
 * newest record leads. Data-driven — no tiers; an artist ranks by their
 * records alone. Ties (and artists with no records yet) stay alphabetical.
 */
export function resolveArtistsByActivity(agents: Agent[], albums: AlbumView[]): Agent[] {
  const rank = new Map<string, number>();
  albums.forEach((album, i) => {
    for (const id of album.artistIds) {
      if (!rank.has(id)) rank.set(id, i);
    }
  });
  return resolveArtists(agents).sort(
    (a, b) => (rank.get(a.id) ?? albums.length) - (rank.get(b.id) ?? albums.length),
  );
}

/** Rationale quotes a player has left on releases, newest first. */
export async function rationalesForPlayer(
  agentId: string,
): Promise<{ releaseId: string; releaseTitle: string; quote: string }[]> {
  const releases = await listReleases();
  return releases
    .filter((r) => typeof r.rationales[agentId] === "string")
    .map((r) => ({ releaseId: r.id, releaseTitle: r.title, quote: r.rationales[agentId] }))
    .reverse();
}
