import { ArtImage } from "@/components/ArtImage";

/**
 * A press photo (960×1200 pixel portrait — the acts' came with the design
 * handoff; the staff's are generated by scripts/press_photos_staff.mjs).
 * Prefers the agent's imageUrl (the Neon media copy, content-addressed);
 * in fixture mode that URL 404s and the checked-in copy under
 * public/press/ takes over, so zero-env pages show the same photo.
 */
export function PressPhoto({
  pressSrc,
  imageUrl,
  alt,
  className,
}: {
  /** The checked-in static fallback under /press/. */
  pressSrc: string;
  imageUrl: string | null;
  alt: string;
  className?: string;
}) {
  const fallback = (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={pressSrc} alt={alt} className={className} />
  );
  if (!imageUrl || imageUrl === pressSrc) return fallback;
  return <ArtImage src={imageUrl} alt={alt} className={className} fallback={fallback} />;
}
